version: "3"

services:
    server:
        image: rescuehub/server:latest
        expose:
          - 8080
        depends_on:
          - postgres

    postgres:
        hostname: postgres
        image: rescuehub/postgres:latest
        expose:
          - 5432

    ui:
        image: rescuehub/ui:latest
        depends_on:
          - server
        ports:
          - 80:80


